language: java
jdk: openjdk8

install:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon test --info

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - openjdk-8-jdk